name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Auto merge Dependabot PRs
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label: "auto-merge"
